### ISSUE TITLE
Support for Py3.7?

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-gate#36]
The [numpy==1.22.4](https://github.com/dwavesystems/dwave-gate/blob/44970734dff605d72b5d7b940a319abb5da8f07f/requirements.txt#L1) requirement seems incompatible with Python 3.7:
``ERROR: No matching distribution found for numpy==1.22.4``

Should this repo not support 3.7 (we say [Python versions >=3.7 are supported](https://docs.ocean.dwavesys.com/en/stable/overview/install.html#installing-ocean-tools) for Ocean) or update to something like ``numpy==1.21.6; python_version < '3.8'`` (did not test if compatible with other packages used in this repo)?

**Comment by arcondello** [comment]
The `requirements.txt` are not necessarily synonymous with support, though it would be nice if all of the Python versions we support could install via the requirements.

**Comment by JoelPasvolsky** [comment]
Also, while ``make install`` succeeds in Python 3.9, it fails in 3.7:

```
    from dwave.gate.registers.registers import (
  File "/home/jpasvolsky/Work/MyVirtualEnvironments/dwave_gate_37/dwave-gate/dwave/gate/registers/__init__.py", line 21, in <module>
    from dwave.gate.registers.registers import *
  File "/home/jpasvolsky/Work/MyVirtualEnvironments/dwave_gate_37/dwave-gate/dwave/gate/registers/registers.py", line 37, in <module>
    from dwave.gate.registers.cyregister import cyRegister
ModuleNotFoundError: No module named 'dwave.gate.registers.cyregister'
makefile:31: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by thisac** [comment]
I've had that happen before, and IIRC it got resolved when reinstalling `cgen` and `cython`. Not sure why exactly, but trying installing it from scratch in a 3.7 environment it works fine for me as long as I have those two + `python3.7-dev` installed (Ubuntu 20.04).

**Comment by thisac** [comment]
Closing this since support for Python 3.7 is deprecated. As a side-note, `requirements.txt` now provides dependencies for a working environment in Python>=3.8<=3.11. NumPy doesn't have any releases supporting both 3.8 _and_ 3.12, so for 3.12 a newer version would have to be installed.
