### ISSUE TITLE
State Preparation in dwave.gate

### ISSUE THREAD

**Issue by ACE07-Sev** [dwavesystems/dwave-gate#45]
Greetings D-Wave team,

Hope all are well. I am quite new to this module, and I am trying to see how one can prepare an arbitrary state using `dwave.gate`. I can see that you can use `.set_state` (if I recall the method name correctly), but it doesn't show the algorithm used for creating the circuit to prepare the state.

Can you kindly point me to where this is explored?

**Comment by thisac** [comment]
Hello @ACE07-Sev,

The `Circuit.set_state()` method simply sets the state vector (or matrix) to the requested value directly. It's used by the simulator and can be used as a way of running simulations with arbitrary initial states. State preparations routines, such as [Möttönen State Preparation](https://arxiv.org/abs/quant-ph/0407010) etc., aren't yet supported.

**Comment by ACE07-Sev** [comment]
I see. Thank you for the update!
